# Vizualize And Analyze the Data 
File will analyze the means across different contexts and across different models including different influence of face saliency. Provides with plots of the results and saves them into chosen destination.

You have to pick a metric and provide a string for saving the files.

In [1]:
import os

import numpy as np
import pickle
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib

import pandas as pd
import seaborn as sns
from glob import glob

matplotlib.rcParams.update({'font.size': 15})

### Pick Metric
NSS, SIM, IG, AUC

In [2]:
plot_metric = 'AUC'

In [3]:
# pick directory
save_dir ='../plots/'

In [4]:
os.chdir('data/')

In [5]:
glob(plot_metric+'*.csv')

['AUC_std_face_05.csv',
 'AUC_mean_face_07.csv',
 'AUC_mean_cxt.csv',
 'AUC_mean_face_03.csv',
 'AUC_mean_models.csv',
 'AUC_std_noface.csv',
 'AUC_std_face_03.csv',
 'AUC_mean_face_05.csv',
 'AUC_std_face_07.csv',
 'AUC_mean_noface.csv']

## Pick the Dataset and Load Required Data

## Data Loading

### Load the scores

In [6]:
df = pd.read_csv(plot_metric+'_mean_noface.csv', index_col=[0])
df_f03 = pd.read_csv(plot_metric+'_mean_face_03.csv', index_col=[0])
df_f05 = pd.read_csv(plot_metric+'_mean_face_05.csv', index_col=[0])
df_f07 = pd.read_csv(plot_metric+'_mean_face_07.csv', index_col=[0])

## Change scores into DataFrames
### No Faces Data Frame

In [7]:
df.columns.name='models'
df.index.name='context'

df = df.transpose()
df

context,aim,cas,covsal,gbvs,icf,ik,sun,dg
models,,,,,,,,
all,0.667399,0.694740,0.743704,0.749366,0.714083,0.656940,0.624444,0.774691
person,0.675930,0.705537,0.748337,0.756851,0.724809,0.669288,0.625526,0.785386
no person,0.651460,0.674566,0.735049,0.735382,0.694044,0.633871,0.622424,0.754710
animal,0.658173,0.688424,0.749722,0.754977,0.707857,0.656090,0.592391,0.782197
sports,0.702019,0.743562,0.755804,0.780210,0.742238,0.692848,0.633091,0.802257
electronic,0.660210,0.681332,0.738809,0.744469,0.706599,0.657036,0.624564,0.770191

#### Separate Faces From the rest of the results

In [8]:
# faces = df.loc['faces']
df = df.transpose()
df = df.loc[['aim','cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun', 'dg']]

#### Get Mean Values across Contexts and Models

In [9]:
df = df.transpose()
df['mean context'] = df.mean(axis=1)
df = df.transpose()
df['mean model'] = df.mean(axis=1)
df

models,all,person,no person,animal,sports,electronic,mean model
context,,,,,,,
aim,0.667399,0.675930,0.651460,0.658173,0.702019,0.660210,0.669199
cas,0.694740,0.705537,0.674566,0.688424,0.743562,0.681332,0.698027
covsal,0.743704,0.748337,0.735049,0.749722,0.755804,0.738809,0.745238
gbvs,0.749366,0.756851,0.735382,0.754977,0.780210,0.744469,0.753542
icf,0.714083,0.724809,0.694044,0.707857,0.742238,0.706599,0.714938
ik,0.656940,0.669288,0.633871,0.656090,0.692848,0.657036,0.661012
sun,0.624444,0.625526,0.622424,0.592391,0.633091,0.624564,0.620407
dg,0.774691,0.785386,0.754710,0.782197,0.802257,0.770191,0.778239
mean context,0.703171,0.711458,0.687688,0.698729,0.731504,0.697901,0.705075

In [11]:
df = df.transpose()

In [12]:
df_mean_model = df.loc['mean model']
df_mean_context = df.transpose().loc['mean context']

### Faces with $\alpha$ = 0.3

In [13]:
df_f03.columns.name='models'
df_f03.index.name='context'

# Rename columns of the face plot
col = {'aim_face_03':'aim', 'cas_face_03':'cas', 'covsal_face_03':'covsal', 'gbvs_face_03':'gbvs',
       'icf_face_03':'icf', 'ik_10_face_03':'ik_10', 'sun_face_03':'sun', 'ik_face_03':'ik'}
df_f03 = df_f03.rename(index=str, columns=col).transpose()

df_f03

context,aim,cas,covsal,gbvs,icf,ik,sun
models,,,,,,,
all,0.672630,0.698729,0.746796,0.751947,0.715740,0.662315,0.631391
person,0.683892,0.711624,0.753053,0.760785,0.727315,0.677464,0.636110
no person,0.651590,0.674635,0.735105,0.735434,0.694115,0.634011,0.622574
animal,0.660025,0.689674,0.751149,0.755935,0.708423,0.658087,0.595219
sports,0.704642,0.745200,0.757816,0.781719,0.743268,0.695549,0.637396
electronic,0.666772,0.686698,0.743390,0.747994,0.709048,0.663965,0.633686

#### Get Mean Values across Contexts and Models

In [14]:
df_f03['mean context'] = df_f03.mean(axis=1)
df_f03 = df_f03.transpose()
df_f03['mean model'] = df_f03.mean(axis=1)
df_f03 = df_f03.transpose()
df_f03

context,aim,cas,covsal,gbvs,icf,ik,sun,mean context
models,,,,,,,,
all,0.672630,0.698729,0.746796,0.751947,0.715740,0.662315,0.631391,0.697078
person,0.683892,0.711624,0.753053,0.760785,0.727315,0.677464,0.636110,0.707177
no person,0.651590,0.674635,0.735105,0.735434,0.694115,0.634011,0.622574,0.678209
animal,0.660025,0.689674,0.751149,0.755935,0.708423,0.658087,0.595219,0.688359
sports,0.704642,0.745200,0.757816,0.781719,0.743268,0.695549,0.637396,0.723656
electronic,0.666772,0.686698,0.743390,0.747994,0.709048,0.663965,0.633686,0.693079
mean model,0.673258,0.701093,0.747885,0.755636,0.716318,0.665232,0.626062,0.697926

In [15]:
df_f03_mean_model = df_f03.loc['mean model']
df_f03_mean_context = df_f03.transpose().loc['mean context']

### Faces with $\alpha$ = 0.5

In [16]:
df_f05.columns.name='models'
df_f05.index.name='context'

# Rename columns of the face plot
col = {'aim_face_05':'aim', 'cas_face_05':'cas', 'covsal_face_05':'covsal', 'gbvs_face_05':'gbvs',
       'icf_face_05':'icf', 'ik_10_face_05':'ik_10', 'sun_face_05':'sun', 'ik_face_05':'ik'}
df_f05 = df_f05.rename(index=str, columns=col).transpose()

df_f05

context,aim,cas,covsal,gbvs,icf,ik,sun
models,,,,,,,
all,0.673422,0.700353,0.747907,0.752648,0.716269,0.663518,0.633186
person,0.685102,0.714109,0.754747,0.761860,0.728127,0.679300,0.638852
no person,0.651602,0.674653,0.735129,0.735436,0.694113,0.634032,0.622601
animal,0.660316,0.690178,0.751623,0.756197,0.708662,0.658585,0.595998
sports,0.705129,0.745823,0.758670,0.782176,0.743702,0.696291,0.638744
electronic,0.667845,0.688780,0.745088,0.748975,0.709841,0.665551,0.635894

#### Get Mean Values across Contexts and Models

In [17]:
df_f05['mean context'] = df_f05.mean(axis=1)
df_f05 = df_f05.transpose()
df_f05['mean model'] = df_f05.mean(axis=1)
df_f05 = df_f05.transpose()
df_f05

context,aim,cas,covsal,gbvs,icf,ik,sun,mean context
models,,,,,,,,
all,0.673422,0.700353,0.747907,0.752648,0.716269,0.663518,0.633186,0.698186
person,0.685102,0.714109,0.754747,0.761860,0.728127,0.679300,0.638852,0.708871
no person,0.651602,0.674653,0.735129,0.735436,0.694113,0.634032,0.622601,0.678224
animal,0.660316,0.690178,0.751623,0.756197,0.708662,0.658585,0.595998,0.688794
sports,0.705129,0.745823,0.758670,0.782176,0.743702,0.696291,0.638744,0.724362
electronic,0.667845,0.688780,0.745088,0.748975,0.709841,0.665551,0.635894,0.694568
mean model,0.673903,0.702316,0.748861,0.756215,0.716786,0.666213,0.627546,0.698834

In [18]:
df_f05_mean_model = df_f05.loc['mean model']
df_f05_mean_context = df_f05.transpose().loc['mean context']

### Faces with $\alpha$ = 0.7

In [19]:
df_f07.columns.name='models'
df_f07.index.name='context'

# Rename columns of the face plot
col = {'aim_face_07':'aim', 'cas_face_07':'cas', 'covsal_face_07':'covsal', 'gbvs_face_07':'gbvs',
       'icf_face_07':'icf', 'ik_10_face_07':'ik_10', 'sun_face_07':'sun', 'ik_face_07':'ik'}
df_f07 = df_f07.rename(index=str, columns=col).transpose()

df_f07

context,aim,cas,covsal,gbvs,icf,ik,sun
models,,,,,,,
all,0.674163,0.701140,0.749089,0.752909,0.716903,0.664329,0.634122
person,0.686218,0.715308,0.756504,0.762269,0.729096,0.680528,0.640278
no person,0.651640,0.674669,0.735235,0.735422,0.694122,0.634062,0.622619
animal,0.660701,0.690495,0.752197,0.756329,0.709061,0.659037,0.596435
sports,0.705678,0.746190,0.759735,0.782433,0.744237,0.696871,0.639483
electronic,0.668927,0.689888,0.746879,0.749367,0.710843,0.666733,0.637194

In [20]:
df_f07['mean context'] = df_f07.mean(axis=1)
df_f07 = df_f07.transpose()
df_f07['mean model'] = df_f07.mean(axis=1)
df_f07 = df_f07.transpose()
df_f07

context,aim,cas,covsal,gbvs,icf,ik,sun,mean context
models,,,,,,,,
all,0.674163,0.701140,0.749089,0.752909,0.716903,0.664329,0.634122,0.698951
person,0.686218,0.715308,0.756504,0.762269,0.729096,0.680528,0.640278,0.710029
no person,0.651640,0.674669,0.735235,0.735422,0.694122,0.634062,0.622619,0.678253
animal,0.660701,0.690495,0.752197,0.756329,0.709061,0.659037,0.596435,0.689179
sports,0.705678,0.746190,0.759735,0.782433,0.744237,0.696871,0.639483,0.724947
electronic,0.668927,0.689888,0.746879,0.749367,0.710843,0.666733,0.637194,0.695690
mean model,0.674555,0.702949,0.749940,0.756455,0.717377,0.666927,0.628355,0.699508

In [21]:
df_f07_mean_model = df_f07.loc['mean model']
df_f07_mean_context = df_f07.transpose().loc['mean context']

### Create Mean Matrices

In [24]:
mean_models = pd.DataFrame([df_mean_model, df_f03_mean_model, df_f05_mean_model, df_f07_mean_model], index=[0,0.3,0.5,0.7])

# mean_models = mean_models.transpose()
mean_models = mean_models.loc[['all', 'person', 'no person', 'animal', 'electronic', 'sports']]
mean_models

KeyError: "None of [Index(['all', 'person', 'no person', 'animal', 'electronic', 'sports'], dtype='object')] are in the [index]"

In [23]:
mean_contexts = pd.DataFrame([df_mean_context, df_f03_mean_context, df_f05_mean_context, df_f07_mean_context], index=[0,0.3,0.5,0.7])

mean_contexts = mean_contexts.transpose()
mean_contexts = mean_contexts.loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']]
mean_contexts

KeyError: "None of [Index(['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun'], dtype='object', name='models')] are in the [index]"

## Visualization of The Results

### Data Prep For separate Vizualization

In [ ]:
df0 = df.loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']]
df0 = df0.transpose().loc[['all', 'person', 'no person', 'animal','electronic', 'sports']]

df0_mean_context = df.transpose().loc[['mean context']]
df0_mean_context = df0_mean_context.transpose().loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']].transpose()

df0_mean_model = df.loc[['mean model']]
df0_mean_model = df0_mean_model.transpose().loc[['all', 'person', 'no person', 'animal','electronic', 'sports']]

In [ ]:
df0_f03 = df_f03.loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']]
df0_f03 = df0_f03.transpose().loc[['all', 'person', 'no person', 'animal','electronic', 'sports']]

df0_mean_context_f03 = df_f03.transpose().loc[['mean context']]
df0_mean_context_f03 = df0_mean_context_f03.transpose().loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']].transpose()

df0_mean_model_f03 = df_f03.loc[['mean model']]
df0_mean_model_f03 = df0_mean_model_f03.transpose().loc[['all', 'person', 'no person', 'animal','electronic', 'sports']]

In [ ]:
df0_f05 = df_f05.loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']]
df0_f05 = df0_f05.transpose().loc[['all', 'person', 'no person', 'animal','electronic', 'sports']]

df0_mean_context_f05 = df_f05.transpose().loc[['mean context']]
df0_mean_context_f05 = df0_mean_context_f05.transpose().loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']].transpose()

df0_mean_model_f05 = df_f05.loc[['mean model']]
df0_mean_model_f05 = df0_mean_model_f05.transpose().loc[['all', 'person', 'no person', 'animal','electronic', 'sports']]

In [ ]:
df0_f07 = df_f07.loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']]
df0_f06 = df0_f07.transpose().loc[['all', 'person', 'no person', 'animal','electronic', 'sports']]

df0_mean_context_f07 = df_f07.transpose().loc[['mean context']]
df0_mean_context_f07 = df0_mean_context_f07.transpose().loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']].transpose()

df0_mean_model_f07 = df_f07.loc[['mean model']]
df0_mean_model_f07 = df0_mean_model_f07.transpose().loc[['all', 'person', 'no person', 'animal','electronic', 'sports']]

### Make the Big Fancy Plot

In [ ]:
matplotlib.rcParams.update({'font.size': 15})

fig, ax = plt.subplots(figsize=(30,8))
gs = gridspec.GridSpec(2, 8,
                       width_ratios=[7, 1, 7, 1, 7, 1, 7, 1],
                       height_ratios=[6, 1]
                       )

ax01 = plt.subplot(gs[0])
ax02 = plt.subplot(gs[1])
ax03 = plt.subplot(gs[8])

ax11 = plt.subplot(gs[2])
ax12 = plt.subplot(gs[3])
ax13 = plt.subplot(gs[10])

ax21 = plt.subplot(gs[4])
ax22 = plt.subplot(gs[5])
ax23 = plt.subplot(gs[12])

ax31 = plt.subplot(gs[6])
ax32 = plt.subplot(gs[7])
ax33 = plt.subplot(gs[14])

im = sns.heatmap(df0, annot=True, linewidths=.5, ax=ax01, cmap='BuGn', cbar=False, xticklabels='', fmt='.2f');
sns.heatmap(df0_mean_model, annot=True, linewidths=.5, ax=ax02, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');
sns.heatmap(df0_mean_context, annot=True, linewidths=.5, ax=ax03, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');

sns.heatmap(df0_f03, annot=True, linewidths=.5, ax=ax11, cmap='BuGn', cbar=False, xticklabels='');
sns.heatmap(df0_mean_model_f03, annot=True, linewidths=.5, ax=ax12, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');
sns.heatmap(df0_mean_context_f03, annot=True, linewidths=.5, ax=ax13, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');

sns.heatmap(df0_f05, annot=True, linewidths=.5, ax=ax21, cmap='BuGn', cbar=False, xticklabels='', fmt='.2f');
sns.heatmap(df0_mean_model_f05, annot=True, linewidths=.5, ax=ax22, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');
sns.heatmap(df0_mean_context_f05, annot=True, linewidths=.5, ax=ax23, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');

sns.heatmap(df0_f07, annot=True, linewidths=.5, ax=ax31, cmap='BuGn', cbar=False, xticklabels='', fmt='.2f');
sns.heatmap(df0_mean_model_f07, annot=True, linewidths=.5, ax=ax32, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');
sns.heatmap(df0_mean_context_f07, annot=True, linewidths=.5, ax=ax33, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');

ax01.set_xlabel('');
ax02.set_ylabel('');
ax02.set_xlabel('');
ax03.set_ylabel('');

ax11.set_yticklabels('');
ax11.set_xlabel('');
ax11.set_ylabel('')
ax12.set_ylabel('');
ax12.set_xlabel('');
ax13.set_ylabel('');

ax21.set_yticklabels('');
ax21.set_xlabel('');
ax21.set_ylabel('')
ax22.set_ylabel('');
ax22.set_xlabel('');
ax23.set_ylabel('');

ax31.set_yticklabels('');
ax31.set_xlabel('');
ax31.set_ylabel('')
ax32.set_ylabel('');
ax32.set_xlabel('');
ax33.set_ylabel('');

ax01.set_title('{} no face'.format(plot_metric));
ax11.set_title('{} 0.3 face'.format(plot_metric));
ax21.set_title('{} 0.5 face'.format(plot_metric));
ax31.set_title('{} 0.7 face'.format(plot_metric));
# plt.savefig(save_dir+'{}_sep_with_mean.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

In [ ]:
matplotlib.rcParams.update({'font.size': 15})

fig, ax = plt.subplots(figsize=(30,8))
gs = gridspec.GridSpec(2, 8,
                       width_ratios=[7, 1, 7, 1, 7, 1, 7, 1],
                       height_ratios=[6, 1]
                       )

ax01 = plt.subplot(gs[0])
ax02 = plt.subplot(gs[1])
ax03 = plt.subplot(gs[8])

ax11 = plt.subplot(gs[2])
ax12 = plt.subplot(gs[3])
ax13 = plt.subplot(gs[10])

ax21 = plt.subplot(gs[4])
ax22 = plt.subplot(gs[5])
ax23 = plt.subplot(gs[12])

ax31 = plt.subplot(gs[6])
ax32 = plt.subplot(gs[7])
ax33 = plt.subplot(gs[14])
cmap='BuGn'

im = sns.heatmap(df0, annot=True, linewidths=.5, ax=ax01, cmap='BuGn', cbar=False, xticklabels='', fmt='.2f');
sns.heatmap(df0_mean_model, annot=True, linewidths=.5, ax=ax02, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');
sns.heatmap(df0_mean_context, annot=True, linewidths=.5, ax=ax03, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');

sns.heatmap(df0_f03, annot=True, linewidths=.5, ax=ax11, cmap='BuGn', cbar=False, xticklabels='');
sns.heatmap(df0_mean_model_f03, annot=True, linewidths=.5, ax=ax12, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');
sns.heatmap(df0_mean_context_f03, annot=True, linewidths=.5, ax=ax13, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');

sns.heatmap(df0_f05, annot=True, linewidths=.5, ax=ax21, cmap='BuGn', cbar=False, xticklabels='', fmt='.2f');
sns.heatmap(df0_mean_model_f05, annot=True, linewidths=.5, ax=ax22, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');
sns.heatmap(df0_mean_context_f05, annot=True, linewidths=.5, ax=ax23, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');

sns.heatmap(df0_f07, annot=True, linewidths=.5, ax=ax31, cmap='BuGn', cbar=False, xticklabels='', fmt='.2f');
sns.heatmap(df0_mean_model_f07, annot=True, linewidths=.5, ax=ax32, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');
sns.heatmap(df0_mean_context_f07, annot=True, linewidths=.5, ax=ax33, cmap='BuGn', yticklabels='', cbar=False, fmt='.2f');

ax01.set_xlabel('');
ax02.set_ylabel('');
ax02.set_xlabel('');
ax03.set_ylabel('');

ax11.set_yticklabels('');
ax11.set_xlabel('');
ax11.set_ylabel('')
ax12.set_ylabel('');
ax12.set_xlabel('');
ax13.set_ylabel('');

ax21.set_yticklabels('');
ax21.set_xlabel('');
ax21.set_ylabel('')
ax22.set_ylabel('');
ax22.set_xlabel('');
ax23.set_ylabel('');

ax31.set_yticklabels('');
ax31.set_xlabel('');
ax31.set_ylabel('')
ax32.set_ylabel('');
ax32.set_xlabel('');
ax33.set_ylabel('');

ax01.set_title('{} no face'.format(plot_metric));
ax11.set_title('{} 0.3 face'.format(plot_metric));
ax21.set_title('{} 0.5 face'.format(plot_metric));
ax31.set_title('{} 0.7 face'.format(plot_metric));
# plt.savefig(save_dir+'{}_sep_with_mean.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

In [ ]:
matplotlib.rcParams.update({'font.size': 15})

f, ax = plt.subplots(figsize=(11, 9))
sns.heatmap(df, annot=True, linewidths=.5, ax=ax, cmap='BuGn');
plt.title('{} results'.format(plot_metric));

# plt.savefig(save_dir+'{}_all.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

## Visualization of The Means

In [ ]:
matplotlib.rcParams.update({'font.size': 20})

f, ax = plt.subplots(figsize=(11, 9))
sns.heatmap(mean_contexts.transpose(), annot=True, linewidths=.5,cmap='BuGn', ax=ax,fmt='.3f');
plt.ylabel('Weight of face influence')
plt.title('{} scores for different models'.format(plot_metric));
plt.xticks(rotation=90)
# plt.savefig(save_dir+'{}_performance_mean_contexts.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

In [ ]:
f, ax = plt.subplots(figsize=(11, 9))
matplotlib.rcParams.update({'font.size': 20})

sns.heatmap(mean_models.transpose(), annot=True, linewidths=.5, ax=ax,cmap='BuGn',fmt='.3f');
plt.ylabel('Weight of face influence')
plt.title('{} scores of different context'.format(plot_metric));

# plt.savefig(save_dir+'{}_performance_mean_models.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

## Calculate The Relative Error

#### Drop DG for diff

In [ ]:
df1 = df.loc[['aim','cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun', 'mean model']]

In [ ]:
df1

In [ ]:
df_diff_f03 = ((df_f03 - df1) / df1)*100
df_diff_f05 = ((df_f05 - df1) / df1)*100
df_diff_f07 = ((df_f07 - df1) / df1)*100

#### Get mean of models and mean of contexts in diff out

#### Diff Models (analyse across contexts)

In [ ]:
mean_model_diff_f03 = df_diff_f03.loc['mean model']
mean_model_diff_f05 = df_diff_f05.loc['mean model']
mean_model_diff_f07 = df_diff_f07.loc['mean model']

mean_models_diff = pd.DataFrame([mean_model_diff_f03, 
                            mean_model_diff_f05,
                            mean_model_diff_f07], index=[0.3,0.5,0.7])

mean_models_diff = mean_models_diff.transpose()
mean_models_diff

#### Diff Contexts (analyse across models)

In [ ]:
mean_context_diff_f03 = df_diff_f03.transpose().loc['mean context']
mean_context_diff_f05 = df_diff_f05.transpose().loc['mean context']
mean_context_diff_f07 = df_diff_f07.transpose().loc['mean context']

mean_context_diff = pd.DataFrame([mean_context_diff_f03, 
                            mean_context_diff_f05,
                            mean_context_diff_f07], index=[0.3,0.5,0.7])

mean_context_diff = mean_context_diff.transpose()
mean_context_diff

## Vizualize relative errors

In [ ]:
fig, ax = plt.subplots(1, 3,figsize=(25,5), sharex=True, sharey=True)

im = sns.heatmap(df_diff_f03, annot=True, linewidths=.5, ax=ax[0], cbar=False);
sns.heatmap(df_diff_f05, annot=True, linewidths=.5, ax=ax[1], cbar=False);
sns.heatmap(df_diff_f07, annot=True, linewidths=.5, ax=ax[2], cbar=False);

mappable = im.get_children()[0]
plt.colorbar(mappable, ax = ax);

ax[0].set_title('{} rel err f03'.format(plot_metric));
ax[1].set_title('{} rel err f05'.format(plot_metric));
ax[2].set_title('{} rel err f07'.format(plot_metric));

# plt.savefig(save_dir+'{}_sep_diff_with_mean.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

In [ ]:
f, ax = plt.subplots(figsize=(11, 9))
sns.heatmap(mean_context_diff.transpose(), annot=True, linewidths=.5, ax=ax);
plt.title('{} mean_models relative error'.format(plot_metric));
# plt.savefig(save_dir+'{}_mean_contexts_diff.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

### Bar Plot Vizualization for Different $\alpha$ Wace Weight

In [ ]:
mean_context_diff = mean_context_diff.loc[['aim', 'cas', 'covsal', 'gbvs', 'icf', 'ik', 'sun']]

matplotlib.rcParams.update({'font.size': 20})

fig, ax = plt.subplots(figsize=(11,9));
mean_context_diff.plot.bar(ax=ax);
# plt.title('Weight of face influence')
plt.ylabel('{} score change [%]'.format(plot_metric));
plt.grid(alpha=0.3)


# plt.savefig(save_dir+'{}_improvment_mean_contexts.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

In [ ]:
mean_models_diff = mean_models_diff.loc[['all', 'person', 'no person', 'animal', 'electronic', 'sports']]

matplotlib.rcParams.update({'font.size': 20})
fig, ax = plt.subplots(figsize=(11,9));
mean_models_diff.plot.bar(ax=ax);

plt.grid(alpha=0.3)
# plt.title('Weight of face influence')
plt.ylabel('{} score change [%]'.format(plot_metric));


# plt.savefig(save_dir+'{}_improvment_mean_model.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

### Merge The Plots

In [ ]:
fig, ax = plt.subplots(1, 2, figsize=(25,9), sharex=False, sharey=True)

mean_context_diff.plot.bar(ax=ax[0]);
mean_models_diff.plot.bar(ax=ax[1]);

mappable = im.get_children()[0]

ax[0].set_title('score change across models')
ax[1].set_title('score change across contexts')

ax[0].grid(alpha=0.5)
ax[1].grid(alpha=0.5)

ax[0].tick_params(labelrotation=90)
ax[1].tick_params(labelrotation=90)

ax[0].set_ylabel('{} score change [%]'.format(plot_metric));


# plt.savefig(save_dir+'{}_improvements_mean_both.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)

In [ ]:
fig, ax = plt.subplots(1, 2, figsize=(25,9), sharex=False, sharey=True)

im = sns.heatmap(mean_contexts.transpose(), annot=True, linewidths=.5, ax=ax[0], cbar=False, cmap='BuGn');
sns.heatmap(mean_models.transpose(), annot=True, linewidths=.5, ax=ax[1], cbar=False, cmap='BuGn');

mappable = im.get_children()[0]
plt.colorbar(mappable, ax = ax);

ax[0].set_title('mean NSS score across models'.format(plot_metric))
ax[1].set_title('mean NSS score across contexts'.format(plot_metric))

ax[0].tick_params(labelrotation=90)
ax[1].tick_params(labelrotation=90)

ax[0].set_ylabel(r'$\alpha$ face weight')

# plt.savefig(save_dir+'NSS_performance_mean_both.jpg'.format(plot_metric), bbox_inches='tight', pad_inches=0)