# Vizualize And Analyze the Data 
You have to pick a metric and provide a string for saving the files.

Notebook loads the dataframes and focuses on vizualization of means.

In [1]:
import os
os.chdir('./data')

import numpy as np
import pickle
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib

import pandas as pd
import seaborn as sns
from glob import glob

matplotlib.rcParams.update({'font.size': 15})

### Pick Metric
NSS, SIM, IG, AUC

In [2]:
plot_metric = 'SIM'

In [3]:
df = pd.read_csv('scores_' + plot_metric + '.csv')
df_feaces = pd.read_csv('scores_faces_' + plot_metric + '.csv')
df_f03 = pd.read_csv('scores_f03_' + plot_metric + '.csv')
df_f05 = pd.read_csv('scores_f05_' + plot_metric + '.csv')
df_f07 = pd.read_csv('scores_f07_' + plot_metric + '.csv')
mean_models = pd.read_csv('scores_mean_models_' + plot_metric + '.csv')
mean_contexts = pd.read_csv('scores_mean_contexts_' + plot_metric + '.csv')

In [4]:
df

,models,all,person,no person,animal,electronic,sports,mean context
0,aim,0.529256,0.504981,0.568607,0.472232,0.535764,0.478441,0.514880
1,cas,0.521473,0.496486,0.561978,0.459220,0.525020,0.490274,0.509075
2,covsal,0.528376,0.520976,0.540371,0.516241,0.507251,0.502744,0.519326
3,gbvs,0.579692,0.547139,0.632463,0.532250,0.586402,0.524310,0.567043
4,icf,0.540450,0.520813,0.572283,0.480500,0.534348,0.493894,0.523715
5,ik,0.483443,0.458229,0.524316,0.440349,0.498116,0.439303,0.473959
6,sun,0.436436,0.400730,0.494317,0.374971,0.449312,0.347440,0.417201
7,dg,0.642767,0.630332,0.662924,0.623571,0.637034,0.623714,0.636724
8,mean model,0.532737,0.509961,0.569657,0.487417,0.534156,0.487515,0.520240